module.exports = Object.freeze({
  array: "ARRAY",
  boolean: "BOOLEAN",
  break: "BREAK",
  char: "CHAR",
  continue: "CONTINUE",
  do: "DO",
  else: "ELSE",
  false: "FALSE",
  function: "FUNCTION",
  if: "IF",
  integer: "INTEGER",
  of: "OF",
  string: "STRING",
  struct: "STRUCT",
  true: "TRUE",
  type: "TYPE",
  var: "VAR",
  while: "WHILE",
  return: "RETURN",
})
