module.exports = Object.freeze({
  ":": "COLON",
  ";": "SEMI_COLON",
  ",": "COMMA",
  "=": "EQUALS",
  "[": "LEFT_SQUARE",
  "]": "RIGHT_SQUARE",
  "{": "LEFT_BRACES",
  "}": "RIGHT_BRACES",
  "(": "LEFT_PARENTHESIS",
  ")": "RIGHT_PARENTHESIS",
  "&&": "AND",
  "||": "OR",
  "<": "LESS_THAN",
  ">": "GREATER_THAN",
  "<=": "LESS_OR_EQUAL",
  ">=": "GREATER_OR_EQUAL",
  "!=": "NOT_EQUAL",
  "==": "EQUAL_EQUAL",
  "+": "PLUS",
  "++": "PLUS_PLUS",
  "-": "MINUS",
  "--": "MINUS_MINUS",
  "*": "TIMES",
  "/": "DIVIDE",
  ".": "DOT",
  "!": "NOT",
})
